import { httpJson } from '../http';

const BASE_URL =
  process.env.EXPO_PUBLIC_GCP3_BACKEND_URL ||
  process.env.EXPO_PUBLIC_BACKEND_URL ||
  'http://localhost:8000';

// --- Shared types (hand-typed until openapi-typescript codegen is wired) ---
// AUTOGENERATED shapes live in gcp3.types.ts once `npm run gen:types` runs.
// These types reflect the actual backend response shapes as of 2026-05-25.

// Raw backend shapes (nested)
interface _RawIndex {
  price: number;
  change: number;
  change_pct: number;
  high?: number;
  low?: number;
  open?: number;
  prev_close?: number;
  symbol?: string;
}

interface _RawOverview {
  brief?: {
    date?: string;
    avg_change_pct?: number;
    market_tone?: string;
    summary?: string;
    indices?: Record<string, _RawIndex>;
    metrics_52w?: Record<string, { low_52week?: number; high_52week?: number }>;
  };
  ai_summary?: {
    brief?: string;
    market_tone?: string;
    macro_regime?: string;
    leading_sectors?: string[];
    lagging_sectors?: string[];
    breadth_pct?: number;
    news_sentiment?: string;
    date?: string;
  };
  sentiment?: {
    overall_sentiment?: string;
    avg_sentiment_score?: number;
    total_articles?: number;
    positive_count?: number;
    negative_count?: number;
    neutral_count?: number;
    ai_narrative?: string;
    date?: string;
  };
}

interface _RawIndicator {
  ticker?: string;
  label?: string;
  price?: number;
  change?: number;
  change_pct?: number;
  category?: string;
  error?: string;
}

interface _RawMacro {
  date?: string;
  ai_regime?: string;
  ai_regime_score?: number;
  ai_summary?: string;
  ai_signals?: string[];
  indicators?: Record<string, _RawIndicator>;
  by_category?: Record<string, _RawIndicator[]>;
}

interface _RawSignalEntry {
  ticker?: string;
  price?: number;
  ai_action?: string;
  ai_score?: number;
  ai_confidence?: string;
  ai_outlook?: string;
  bull_count?: number;
  bear_count?: number;
  signal_count?: number;
  industry?: string;
  returns?: Record<string, number>;
}

interface _RawSignals {
  buys?: _RawSignalEntry[];
  sells?: _RawSignalEntry[];
  holds?: _RawSignalEntry[];
}

// Normalised shapes consumed by BriefingScreen
export interface MarketOverview {
  market_status: string;
  sp500?: number;
  nasdaq?: number;
  dow?: number;
  vix?: number;
  summary?: string;
  ai_brief?: string;
  regime?: string;
  leading_sectors?: string[];
  lagging_sectors?: string[];
  news_sentiment?: string;
  sentiment_summary?: string;
}

export interface MacroPulse {
  sentiment: 'bullish' | 'bearish' | 'neutral';
  score?: number;
  summary?: string;
  updated_at?: string;
  signals?: string[];
  indicators?: Array<{ label: string; ticker: string; price?: number; change_pct?: number; error?: string }>;
}

export interface Signal {
  ticker: string;
  signal: 'buy' | 'sell' | 'hold';
  confidence?: number;
  reason?: string;
  created_at?: string;
}

// Normalisation helpers
function normaliseOverview(raw: _RawOverview): MarketOverview {
  const idx = raw.brief?.indices ?? {};
  const sp = idx['S&P 500'];
  const nq = idx['Nasdaq 100'];
  const dw = idx['Dow Jones'];
  const tone = (raw.brief?.market_tone ?? raw.ai_summary?.market_tone ?? 'unknown').toLowerCase();
  const statusMap: Record<string, string> = { bullish: 'Open — Bullish', bearish: 'Open — Bearish' };
  return {
    market_status: statusMap[tone] ?? `Open — ${tone.charAt(0).toUpperCase() + tone.slice(1)}`,
    sp500: sp?.price,
    nasdaq: nq?.price,
    dow: dw?.price,
    summary: raw.brief?.summary,
    ai_brief: raw.ai_summary?.brief,
    regime: raw.ai_summary?.macro_regime,
    leading_sectors: raw.ai_summary?.leading_sectors,
    lagging_sectors: raw.ai_summary?.lagging_sectors,
    news_sentiment: raw.ai_summary?.news_sentiment,
    sentiment_summary: raw.sentiment?.ai_narrative,
  };
}

function normaliseMacro(raw: _RawMacro): MacroPulse {
  const score = raw.ai_regime_score ?? 0;
  let sentiment: MacroPulse['sentiment'] = 'neutral';
  if (score > 0) sentiment = 'bullish';
  else if (score < 0) sentiment = 'bearish';

  const indicators = Object.values(raw.indicators ?? {})
    .filter((ind) => !ind.error && ind.price != null)
    .map((ind) => ({
      label: ind.label ?? ind.ticker ?? '',
      ticker: ind.ticker ?? '',
      price: ind.price,
      change_pct: ind.change_pct,
    }));

  return {
    sentiment,
    score: raw.ai_regime_score,
    summary: raw.ai_summary,
    updated_at: raw.date,
    signals: raw.ai_signals,
    indicators,
  };
}

function normaliseSignals(raw: _RawSignals | Signal[]): Signal[] {
  // Handle both the new nested shape and a flat array (fallback)
  if (Array.isArray(raw)) return raw;
  const entries: Signal[] = [];
  const add = (list: _RawSignalEntry[] | undefined, action: 'buy' | 'sell' | 'hold') => {
    (list ?? []).forEach((s) => {
      if (s.ticker) {
        entries.push({
          ticker: s.ticker,
          signal: action,
          confidence: s.ai_score != null ? Math.min(Math.abs(s.ai_score), 1) : undefined,
          reason: s.ai_outlook?.slice(0, 120),
        });
      }
    });
  };
  add(raw.buys, 'buy');
  add(raw.sells, 'sell');
  add(raw.holds, 'hold');
  return entries;
}

export interface SwingPrediction {
  ticker: string;
  direction: 'up' | 'down';
  confidence?: number;
  target_price?: number;
  timeframe?: string;
}

export interface EarningsEvent {
  ticker: string;
  report_date: string;
  estimate_eps?: number;
  actual_eps?: number;
}

export interface IndustryReturn {
  sector: string;
  return_1d?: number;
  return_1w?: number;
  return_1m?: number;
}

export interface AgentRunResponse {
  run_id: string;
  status: 'pending' | 'running' | 'complete' | 'error';
  result?: unknown;
}

// --- Client functions ---

export function getMarketOverview(): Promise<MarketOverview> {
  return httpJson<_RawOverview>(BASE_URL, '/market-overview', { timeoutMs: 8_000 }).then(normaliseOverview);
}

export function getMacroPulse(): Promise<MacroPulse> {
  return httpJson<_RawMacro>(BASE_URL, '/macro-pulse', { timeoutMs: 8_000 }).then(normaliseMacro);
}

export function getSignals(): Promise<Signal[]> {
  return httpJson<_RawSignals | Signal[]>(BASE_URL, '/signals', { timeoutMs: 8_000 }).then(normaliseSignals);
}

export function getSignal(ticker: string): Promise<Signal> {
  return httpJson<Signal>(BASE_URL, `/signals/${ticker}`, { timeoutMs: 5_000 });
}

export function getSwingPredictions(): Promise<SwingPrediction[]> {
  return httpJson<SwingPrediction[]>(BASE_URL, '/swing-predictions', { timeoutMs: 5_000 });
}

export function getScreener(params?: Record<string, string>): Promise<unknown[]> {
  return httpJson<unknown[]>(BASE_URL, '/screener', { params, timeoutMs: 5_000 });
}

export function getEarningsRadar(): Promise<EarningsEvent[]> {
  return httpJson<EarningsEvent[]>(BASE_URL, '/earnings-radar', { timeoutMs: 5_000 });
}

export function getIndustryReturns(): Promise<IndustryReturn[]> {
  return httpJson<IndustryReturn[]>(BASE_URL, '/industry-returns', { timeoutMs: 5_000 });
}

export function getIndustryIntel(): Promise<unknown> {
  return httpJson<unknown>(BASE_URL, '/industry-intel', { timeoutMs: 5_000 });
}

export function getContent(): Promise<unknown> {
  return httpJson<unknown>(BASE_URL, '/content', { timeoutMs: 5_000 });
}

export function startAgentRun(
  kind: 'swing' | 'growth',
  payload?: Record<string, unknown>
): Promise<AgentRunResponse> {
  return httpJson<AgentRunResponse>(BASE_URL, `/agents/${kind}/run`, {
    method: 'POST',
    body: payload ?? {},
    timeoutMs: 30_000,
  });
}

export function getAgentRun(
  kind: 'swing' | 'growth',
  runId: string
): Promise<AgentRunResponse> {
  return httpJson<AgentRunResponse>(BASE_URL, `/agents/${kind}/${runId}`, { timeoutMs: 10_000 });
}

export function chatAgentRun(
  kind: 'swing' | 'growth',
  runId: string,
  message: string
): Promise<{ reply: string }> {
  return httpJson<{ reply: string }>(BASE_URL, `/agents/${kind}/${runId}/chat`, {
    method: 'POST',
    body: { message },
    timeoutMs: 30_000,
  });
}

export function healthGcp3(): Promise<{ status: string }> {
  return httpJson<{ status: string }>(BASE_URL, '/health', { timeoutMs: 3_000 });
}
