import { httpJson } from '../http';

const BASE_URL =
  process.env.EXPO_PUBLIC_GCP3_BACKEND_URL ||
  process.env.EXPO_PUBLIC_BACKEND_URL ||
  'http://localhost:8000';

// --- Shared types (hand-typed until openapi-typescript codegen is wired) ---
// AUTOGENERATED shapes live in gcp3.types.ts once `npm run gen:types` runs.
// These minimal types are enough for the initial mobile integration.

export interface MarketOverview {
  market_status: string;
  sp500?: number;
  nasdaq?: number;
  dow?: number;
  vix?: number;
  summary?: string;
}

export interface MacroPulse {
  sentiment: 'bullish' | 'bearish' | 'neutral';
  score?: number;
  summary?: string;
  updated_at?: string;
}

export interface Signal {
  ticker: string;
  signal: 'buy' | 'sell' | 'hold';
  confidence?: number;
  reason?: string;
  created_at?: string;
}

export interface SwingPrediction {
  ticker: string;
  direction: 'up' | 'down';
  confidence?: number;
  target_price?: number;
  timeframe?: string;
}

export interface EarningsEvent {
  ticker: string;
  report_date: string;
  estimate_eps?: number;
  actual_eps?: number;
}

export interface IndustryReturn {
  sector: string;
  return_1d?: number;
  return_1w?: number;
  return_1m?: number;
}

export interface AgentRunResponse {
  run_id: string;
  status: 'pending' | 'running' | 'complete' | 'error';
  result?: unknown;
}

// --- Client functions ---

export function getMarketOverview(): Promise<MarketOverview> {
  return httpJson<MarketOverview>(BASE_URL, '/market-overview', { timeoutMs: 5_000 });
}

export function getMacroPulse(): Promise<MacroPulse> {
  return httpJson<MacroPulse>(BASE_URL, '/macro-pulse', { timeoutMs: 5_000 });
}

export function getSignals(): Promise<Signal[]> {
  return httpJson<Signal[]>(BASE_URL, '/signals', { timeoutMs: 5_000 });
}

export function getSignal(ticker: string): Promise<Signal> {
  return httpJson<Signal>(BASE_URL, `/signals/${ticker}`, { timeoutMs: 5_000 });
}

export function getSwingPredictions(): Promise<SwingPrediction[]> {
  return httpJson<SwingPrediction[]>(BASE_URL, '/swing-predictions', { timeoutMs: 5_000 });
}

export function getScreener(params?: Record<string, string>): Promise<unknown[]> {
  return httpJson<unknown[]>(BASE_URL, '/screener', { params, timeoutMs: 5_000 });
}

export function getEarningsRadar(): Promise<EarningsEvent[]> {
  return httpJson<EarningsEvent[]>(BASE_URL, '/earnings-radar', { timeoutMs: 5_000 });
}

export function getIndustryReturns(): Promise<IndustryReturn[]> {
  return httpJson<IndustryReturn[]>(BASE_URL, '/industry-returns', { timeoutMs: 5_000 });
}

export function getIndustryIntel(): Promise<unknown> {
  return httpJson<unknown>(BASE_URL, '/industry-intel', { timeoutMs: 5_000 });
}

export function getContent(): Promise<unknown> {
  return httpJson<unknown>(BASE_URL, '/content', { timeoutMs: 5_000 });
}

export function startAgentRun(
  kind: 'swing' | 'growth',
  payload?: Record<string, unknown>
): Promise<AgentRunResponse> {
  return httpJson<AgentRunResponse>(BASE_URL, `/agents/${kind}/run`, {
    method: 'POST',
    body: payload ?? {},
    timeoutMs: 30_000,
  });
}

export function getAgentRun(
  kind: 'swing' | 'growth',
  runId: string
): Promise<AgentRunResponse> {
  return httpJson<AgentRunResponse>(BASE_URL, `/agents/${kind}/${runId}`, { timeoutMs: 10_000 });
}

export function chatAgentRun(
  kind: 'swing' | 'growth',
  runId: string,
  message: string
): Promise<{ reply: string }> {
  return httpJson<{ reply: string }>(BASE_URL, `/agents/${kind}/${runId}/chat`, {
    method: 'POST',
    body: { message },
    timeoutMs: 30_000,
  });
}

export function healthGcp3(): Promise<{ status: string }> {
  return httpJson<{ status: string }>(BASE_URL, '/health', { timeoutMs: 3_000 });
}
